apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-frontend
  labels:
    app: {{ include "genai-cloudops.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "genai-cloudops.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "genai-cloudops.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-cloudops.fullname" . }}-frontend
spec:
  selector:
    app: {{ include "genai-cloudops.fullname" . }}-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
  type: {{ .Values.frontend.service.type }} 